### ISSUE TITLE
Question: Return focus

### ISSUE THREAD

**Issue by DavidLGoldberg** [blakeembrey/atom-dash#11]
This isn't a huge deal.  But I was just curious if there was a way to return focus after ctrl+h is pressed, to the atom window.  When I use the HUD and alt+d to open dash and escape out it returns focus to atom, but with ctrl+h it doesn't.  Not a big issue.  Great Package!

**Comment by blakeembrey** [comment]
That would be nice, unfortunately I'm not sure why this is the case. Focus is going back to the Atom window, perhaps it's something Atom can look into? I'm just not sure how I can fix it unless you have some thoughts?

**Comment by blakeembrey** [comment]
@DavidLGoldberg Could you try the latest version and let me know if it's fixed? It appears to have fixed up with the latest Atom version already.

**Comment by DavidLGoldberg** [comment]
:+1: Awesome!  Worked for me as well!
