### ISSUE TITLE
Use the `atom-text-editor` tag instead of the `editor` class.

### ISSUE THREAD

**Issue by roidriscoll** [blakeembrey/atom-dash#13]
In keymaps/dash.cson: Use the `atom-text-editor` tag instead of the `editor` class.

**Comment by blakeembrey** [comment]
Not sure what you're looking at? I updated it a couple of months ago (https://github.com/blakeembrey/atom-dash/blob/master/keymaps/dash.cson). Let me know if I'm misunderstanding you :smile:
