### ISSUE TITLE
Call Dash without activating it

### ISSUE THREAD

**Issue by Kapeli** [blakeembrey/atom-dash#14]
atom-dash calls Dash by opening a `dash-plugin://` URL. The problem is that the system forces Dash to become active when this URL is opened.

Currently, this is not an issue. However, a future update of Dash will add support for iOS remotes. While an iOS remote is connected, extensions are redirected to it directly and Dash on OS X is not shown at all. Unfortunately there's no way for me to prevent the system from activating Dash when you open the `dash-plugin://` URL.

You currently open Dash by running:
```
shell.openExternal(@createLink(string, language)) 
```

I have no idea what this does behind the scenes, but it should be the equivalent of this Terminal command:

```
open dash-plugin://query
```

Instead of that, you should perform the equivalent of this Terminal command:
```
open -g dash-plugin://query
```

The `-g` causes Dash to not get activated if it does not want to and the user experience is a lot better as the active app (Atom) does not lose focus anymore. When you make the change, please make sure to test whether or not you need to escape special symbols (e.g. `$`).

It is safe to make this change as soon as possible (no need to wait for a Dash update), as the current version of Dash already knows to activate itself if it needs to.

**Comment by blakeembrey** [comment]
@Kapeli Thanks for the update, I'll fix this ASAP :+1:

**Comment by blakeembrey** [comment]
Patched with https://github.com/blakeembrey/atom-dash/commit/8a3152abd5e95dc7dd8f449d717ce133581778b3

**Comment by Kapeli** [comment]
Thank you! :+1:
