### ISSUE TITLE
Getting deprecated calls – see #6278

### ISSUE THREAD

**Issue by clauseggers** [blakeembrey/atom-dash#15]
Getting deprecated calls from atom-dash, please see:
https://github.com/atom/atom/issues/6278

**Comment by blakeembrey** [comment]
Thanks for the heads up. I've patched all the deprecation calls I could see and released `v1.1.1`. Let me know if this works for you :+1:

**Comment by clauseggers** [comment]
Thanks for patching this Blake – it works :-)
