### ISSUE TITLE
Gruntfile.js

### ISSUE THREAD

**Issue by tamaspiros** [blakeembrey/atom-dash#16]
Is it currently possible to add a config setting in Atom so that when I have a `Gruntfile.js` open the Dash opens the Grunt documentation instead of the JavaScript one?

(Of course this could be applied to gulp.js as well for example)

**Comment by blakeembrey** [comment]
That makes perfect sense to me and I think it's a great suggestion :+1: Right now there's no file level override, but it would be easy enough to add. I'll try to get around it in the next couple of weeks :smile:

**Comment by tamaspiros** [comment]
Nice - thanks for the fast response. I tried to play around with the config but saw that it's not possible. Let me know if you need help writing this functionality - I'm happy to help / test etc. :+1:

**Comment by blakeembrey** [comment]
Just released a new minor version with some initial filenames (Grunt and Gulp) to check it out. Feel free to add more :smile:
