### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by underyx** [blakeembrey/atom-dash#18]
Here's a pretty good summary of the issue and how to remedy it: http://keepachangelog.com/

**Comment by blakeembrey** [comment]
Thanks for the link, I'll try to backtrack it ASAP.

**Comment by underyx** [comment]
You're the best, Blake!

**Comment by blakeembrey** [comment]
Let me know how https://github.com/blakeembrey/atom-dash/blob/master/CHANGELOG.md looks :smile: I'll be trying out the same format for my other projects in the future.
