### ISSUE TITLE
Use ruby/rails when editing haml

### ISSUE THREAD

**Issue by lenart** [blakeembrey/atom-dash#23]
Would it make sense to also add `ruby` and `rails` to `haml`'s grammar (https://github.com/blakeembrey/atom-dash/blob/master/lib/grammar-map.coffee#L154)? I often find myself looking for documentation of ruby related methods while working inside haml.

I know I could just clone `atom-dash` and make changes locally but I'm guessing then I'd have to make this changes after each atom-dash update?

**Comment by lenart** [comment]
After playing around a bit more I've managed to achieve the same by editing atom's config (Atom -> Open Your Config) and added the following:

```coffeescript
  "dash":
    "grammars":
      "Ruby Haml": [
        "haml",
        "rails",
        "ruby",
        "rubygems"
      ]
```

**Comment by Kapeli** [comment]
Would it make sense for me to update https://kapeli.com/dash_plugins and include Ruby & Rails for HAML? I think it's quite common to use Ruby in HAML files right?
