### ISSUE TITLE
Atom-Dash not available in Atom's Package Search

### ISSUE THREAD

**Issue by iAm-Eric** [blakeembrey/atom-dash#25]
Hi.
Just as the title says, Atom does not return **Atom-Dash** when using the package search. I tried to use the terms *dash* and *atom-dash*.

Are you aware of this? I tried a few weeks ago as well with the same results.

Thanks,
Eric

**Comment by blakeembrey** [comment]
@iAm-Eric I wasn't aware of this, no, so I'll try looking into it. A basic search from the site seems to work (https://atom.io/packages/search?q=dash and https://atom.io/packages/search?q=atom-dash).

**Comment by blakeembrey** [comment]
I'll look at adding some keywords to the package too, see if that makes searching easier.

**Comment by iAm-Eric** [comment]
What's even more odd is in the web search, the keyword *dash* returns a few results where in the app's search it returns a big fat zero.

**Comment by blakeembrey** [comment]
It appears for me:

![image](https://cloud.githubusercontent.com/assets/1088987/9690659/aa4ae972-52f2-11e5-9803-2d4dc3d69475.png)

![image](https://cloud.githubusercontent.com/assets/1088987/9690663/b6cecd62-52f2-11e5-9e15-e17dc9b62995.png)

Is it possible it's already installed for you?

**Comment by iAm-Eric** [comment]
I am quite new to Atom, so perhaps I am doing something wrong then... Here's a screen of my package search - which doesn't look like yours...

<img width="975" alt="screen shot 2015-09-04 at 19 56 14" src="https://cloud.githubusercontent.com/assets/3150341/9690942/a55a87cc-533f-11e5-8aab-6475aa58aef4.png">

**Comment by blakeembrey** [comment]
@iAm-Eric That's your installed packages. You want to use the "Install" pane, click on "Install" on the left hand side and try searching in there. I think you'll find some more interesting packages too :smile:

**Comment by blakeembrey** [comment]
I'll update the README too. I can see why it's confusing, those instructions were from a long time ago when the panes were merged in Atom.

**Comment by iAm-Eric** [comment]
noooooooooooo.

Wow, man - very sorry! How embarrassing.

**Comment by blakeembrey** [comment]
@iAm-Eric It's alright. I'll close this now. I just had a quick search of GitHub for packages and it seems most packages use the old `Preferences -> Packages` menu, so it's not uncommon. Might be worth pinging other repos to make sure everything is consistent, I suspect most haven't been updated since the settings pane changed.

I'll close this now, I'm assuming you got it working :+1: Feel free to reopen or continue the discussion.
