### ISSUE TITLE
Word selection around cursor seems broken

### ISSUE THREAD

**Issue by tylerb** [blakeembrey/atom-dash#26]
For `regexp.MustCompile()`, with the cursor in the middle of `MustCompile`, pressing `ctrl-h` opens dash and searches for `ustCompile(`. If I select `MustCompile` entirely, then `ctrl-h`, it works as expected.

**Comment by blakeembrey** [comment]
@tylerb Unfortunately I'll probably need more information to be able to test this, but it's likely an Atom bug. I'm using the Atom APIs provided to me to get the text from the editor, so it's likely their buffer is off by one at some point. What language are you using? Can you reproduce it consistently? Is syntax highlighting correct?

**Comment by tylerb** [comment]
No worries! I literally installed Atom and started setting it up for Go half an hour before posting this issue. I didn't really know what information to give or how to find it. I'm happy to answer any questions to help get this figured out. I do a lot of OSS myself. :)

I am using Golang, and I have [go-plus](https://github.com/joefitzgerald/go-plus) installed. Syntax highlighting is correct. I can reproduce it every time. It doesn't matter what the function is.

As you said, it seems to be an off-by-one issue, as it's reproducible with the same results no matter what I'm running it on.

Please let me

**Comment by blakeembrey** [comment]
@tylerb Great, thanks. Seems like it'd be an Atom bug, but do you have a snippet of the file I can use to reproduce? I tried with just the line you said, but it works fine there. Have you closed and reopened the tab, and still have the issue?

**Comment by tylerb** [comment]
In writing a sample for you, I found something new and interesting:

```go
var good = regexp.MustCompile(".*")
var (
	bad = regexp.MustCompile(".*")
)
```

The `good` line works fine. `ctrl-h` on `MustCompile` works as expected. The `bad` line exhibits the problem I described above.

In this example:

```go
type test struct {
	test string
}
```

the same problem occurs for `string`.

**Comment by tylerb** [comment]
Another interesting tidbit: those code snippets work fine if I do it in a new, blank file. So perhaps it has something to do with the fact that it is a Go file.

**Comment by blakeembrey** [comment]
@tylerb Wow, can confirm. It's specifically when I use tabs before, my default of spaces didn't break anything.

Upon investigation, it comes down to grabbing by scope. Specifically, https://github.com/blakeembrey/atom-dash/blob/master/lib/dash.coffee#L46. Even more specifically, `editor.getTextInBufferRange(editor.bufferRangeForScopeAtCursor('support.function.go'))` is the issue. I'll do a little more prying though, since that's a pretty core feature to making this work.

**Comment by tylerb** [comment]
Is this an issue that occurs only for Go? Or is it happening elsewhere for you?

**Comment by blakeembrey** [comment]
@tylerb It looks like it could be an Atom bug in general with text width handling of tabs. Confirmed, it can be reproduced with other languages.

**Comment by tylerb** [comment]
Excellent. I'll go close the other issue then. :)

**Comment by blakeembrey** [comment]
Hmm, it's specifically https://github.com/atom/atom/blob/278e988cca2bba2b0f5f13d1833786ac59cb989e/src/text-editor.coffee#L2565-L2566 but I'm trying to work around it. Basically, they are mixing up the normal buffer and display buffer which have different indexes (E.g. tab width).

**Comment by blakeembrey** [comment]
Hack, hacks everywhere. I'll open the issue at Atom to fix this in the end, but for now I'll make a commit into `atom-dash` to convert buffer positions.

```
e.getTextInBufferRange(e.displayBuffer.bufferRangeForScreenRange(e.displayBuffer.bufferRangeForScopeAtPosition('entity.name.type.js', e.screenPositionForBufferPosition(e.getLastCursor().getBufferPosition()))))
```

Where `e` is the current editor.

**Comment by blakeembrey** [comment]
@tylerb I released a workaround in `v.1.3.1`. I'll make sure it's solved in Atom for future releases.

**Comment by tylerb** [comment]
Awesome! Thank you!
