### ISSUE TITLE
Change of conflicting keybindings

### ISSUE THREAD

**Issue by jsmm** [blakeembrey/atom-dash#27]
This package is very useful because OS X Services don't work in Atom and because of its syntax sensitive search. But this package's default keybindings conflict with the Atom's core keybindings below. 
Is it possible to change atom-dash keybindings?

```
'atom-text-editor':
  'ctrl-alt-h': 'editor:delete-to-beginning-of-subword'
'body .native-key-bindings':
  'ctrl-h': 'native!'
'body':
  'ctrl-h': 'core:backspace'
```
Thanks.

**Comment by blakeembrey** [comment]
You can go to the keymap file from `Atom -> Open Your Keymap` and set it there. What key would you prefer to use?

**Comment by jsmm** [comment]
Yes, I know. But I don't know the parameters to write for atom-dash. Could yo please let me know them?

Usually, packages list them in Settings > Keybindings for them to be copied, modified and written in the file you mention.

**Comment by blakeembrey** [comment]
It should be the ones in here: https://github.com/blakeembrey/atom-dash/blob/master/keymaps/dash.cson. Weird that you don't see them, this is what I see:

![image](https://cloud.githubusercontent.com/assets/1088987/11320940/c937b62a-9060-11e5-9746-d74431c6476f.png)

**Comment by jsmm** [comment]
After writing the keybindings in the keymap, they appear in the list and work. I think they didn't work out of the box because:

- I had overlooked to uncheck the box Enable in the atom-dash package settings.
- Several other packages have their keybindings assigned by default to ctrl-h and ctrl-alt-h.

Thank you for your help to solve this problem.
![atom-dash](https://cloud.githubusercontent.com/assets/2811090/11351687/74bb7f94-9238-11e5-83c3-472d619f5468.jpg)

**Comment by blakeembrey** [comment]
No worries! Glad you've got it sorted out now.

**Comment by sylwiaeb** [comment]
Had the same problem. I installed the package with: `apm install dash` command and didn't see setting for Dash package. Uninstalling and installing again via UI solved the problem.
