### ISSUE TITLE
Any way to maintain window focus on Atom?

### ISSUE THREAD

**Issue by weskoop** [blakeembrey/atom-dash#28]
Any way to add a toggle to keep or return the OS window focus to atom?

This works great for dual screens, but I'm cmd-tabbing after ctrl-h everytime.

**Comment by blakeembrey** [comment]
This was an issue earlier in the year with Atom which was meant to have been resolved: https://github.com/blakeembrey/atom-dash/issues/11. Can you comment and maybe create an issue with Atom if that sounds the same as your problem?

**Comment by weskoop** [comment]
Sounds similar, but it looks like he was dismissing the dash window, and not getting focus back on atom, I'm not dismissing the window, only viewing it on a 2nd monitor.

The focus is switched to Dash (on my 2nd monitor) when ctrl-h is pressed. I don't need to move window focus there, just do the search, and stay (or return) to the editor.

is there a way to spawn the request to dash in the background? or to send the request then pull back window focus?

**Comment by blakeembrey** [comment]
Not that I know of, @Kapeli? I'm sure I can add a separate shortcut if there's a way to do this, but I'm not as up to date on native APIs or CLI options for doing this.

**Comment by blakeembrey** [comment]
Ok, this is from the `man` pages on `open`:

```
     -g  Do not bring the application to the foreground.
```

And in the code I already use this: https://github.com/blakeembrey/atom-dash/blob/master/lib/dash.coffee#L83

**Comment by Kapeli** [comment]
You can add `&prevent_activation=true` to your `dash-plugin://` call to cause Dash not to activate. This only works in the latest version of Dash (3.1.4).

Please don't make this the default as it would appear as if the plugin doesn't work to most users. Add it as an option or separate keyboard shortcut.

**Comment by blakeembrey** [comment]
Yes, of course. Good to know it already exists :+1:

**Comment by blakeembrey** [comment]
Fixed with https://github.com/blakeembrey/atom-dash/releases/tag/v1.4.0. Just use `ctrl+shift+h` now.
