### ISSUE TITLE
Feature request: Read filetype, only search in relevant docs

### ISSUE THREAD

**Issue by joepsz** [blakeembrey/atom-dash#36]
First of all: thanks for making and sharing this! Love it :)

When I `ctrl + h` on the text 'export' while in a .js file, the Ruby docs for the 'export' class open in dash. Is there a way to read the current filetype and tell dash that it should ignore results from irrelevant docs?

**Comment by blakeembrey** [comment]
That should be how it works today. Can you confirm your file is not being detected as Ruby for whatever reason? See https://github.com/blakeembrey/atom-dash/blob/master/lib/dash.coffee#L53 and https://github.com/blakeembrey/atom-dash/blob/master/lib/grammar-map.coffee#L17-L42.
