### ISSUE TITLE
Will not open Zeal

### ISSUE THREAD

**Issue by cwilli34** [blakeembrey/atom-dash#37]
I am using Manjaro Linux (Arch), have Zeal installed, and not matter what I do, it will not open Zeal.  I get errors that look like:
```

Malformed URL
Invalid hostname (character '%' not permitted); source was "query=const Router %3D Ember.Router.extend(%7B%0A    location%3A config.locationType%0A%7D)%3B"; scheme = "dash-plugin", host = ""
```

**Comment by trollixx** [comment]
Sorry, didn't notice this before. Looks like another KDE issue. After some additional testing I've come up to conclusion that we do need to remove `//` in the URL to fix the problem. Unlike #32, I'd suggest doing that for all Linux flavours. `dash-plugin://` is indeed an invalid URL, so removing `//` makes it act similarly to `mailto:` or `skype:` schemes, and so pass the checks.

**Comment by blakeembrey** [comment]
Pushed changes with https://github.com/blakeembrey/atom-dash/commit/137f5b30a96d89e58316fcbdbf8bce4a21726b9d.
