### ISSUE TITLE
Unable to launch Dash

### ISSUE THREAD

**Issue by franj0** [blakeembrey/atom-dash#38]
![selection_040](https://cloud.githubusercontent.com/assets/11553585/17272670/cefb9290-569c-11e6-9374-4c518fdf0fd0.png)

on shortcuts ctrl-h  ctrl-alt-h  ctrl-shift-h

**Comment by blakeembrey** [comment]
I assume you've installed Zeal?

**Comment by franj0** [comment]
Nope, I'm installed "dash" but i think my keyboard is problem.
I have HP Elitebook 8460p with Norway layout keyboard
OS: Linux Ubuntu 14.04
Keyboard for text entry is "Croatian"

[image: Ugrađena slika 2]


[image: Ugrađena slika 1]

2016-08-03 8:20 GMT+02:00 Blake Embrey <notifications@github.com>:

**Comment by blakeembrey** [comment]
It looks like you're on Linux, I wasn't aware that Dash works on Linux?

**Comment by franj0** [comment]
dunno, maybe is some problem with paths, but it's not to important, tnx
anyway

2016-08-03 8:39 GMT+02:00 Blake Embrey <notifications@github.com>:

**Comment by blakeembrey** [comment]
Ok, I'm going to close. Dash is a Mac document viewer, I don't believe there's any version for it on Linux. The Linux compatible version would be to install Zeal.
