### ISSUE TITLE
< gets included as part of an HTML tag

### ISSUE THREAD

**Issue by trollixx** [blakeembrey/atom-dash#39]
In a `.html` file, if cursor is placed between `<` and the tag name (e.g. `span` or `div`), then the following query is passed to Zeal: `html,svg,statamic,javascript,jquery,jqueryui,jquerym,react,nodejs,angularjs,backbone,marionette,meteor,moo,prototype,ember,lodash,underscore,sencha,extjs,titanium,knockout,zepto,cordova,phonegap,yui,unity3d,css,bootstrap,foundation,awesome,cordova,phonegap:<span`. `<span` leads to no results. Moving cursor right fixes the problem.

**Comment by blakeembrey** [comment]
I believe this might be an Atom issue. The plugin used to use syntax to find the current word but it changed with https://github.com/blakeembrey/atom-dash/issues/29 to use Atom's built-in functionality.
