### ISSUE TITLE
Cannot call out the it in atom.

### ISSUE THREAD

**Issue by afghl** [blakeembrey/atom-dash#42]
I installed it and updated `config.cson` file.

however i can't call out it when pressing `ctrl-h`, `ctrl-alt-h` or `ctrl+shift+h`. It wasn't even bind to the key mappings.

my OS is macos,  Did I miss something or does it work in macos? :)

**Comment by blakeembrey** [comment]
Yes, it works on Mac. Dash is only a Mac application. Do you have Mac installed? What exactly did you update (it shouldn't need manual changes)? Do you have Dash installed?

**Comment by afghl** [comment]
embarrassing!!  i restarted atom and it works.  😂 😂 😂  sorry man, closing this issue.
