### ISSUE TITLE
Can't find `cmd.exe` on Windows 10

### ISSUE THREAD

**Issue by tildebyte** [blakeembrey/atom-dash#43]
atom-dash used to work; Since I had to re-image my laptop, it's throwing an error trying to spawn `cmd.exe`. It knows about Zeal, no prob. Maybe Zeal recently added support for `dash://`...? ::shrug::

Sorry I don't have time for a real patch right now, but

```js
join_path = require('path').join
 # snip
      return join_path(process.env.SystemRoot, 'System32', 'cmd.exe') + ' /c start "" "' + uri + '"'
```

gets it working again.

Weirdly, `path = require 'path'` and then `path.join(etc.` does *not* work, but then again, I'm no JS genius.

**Comment by trollixx** [comment]
@blakeembrey I am not an Atom/Electron expert, but shouldn't this extension just use [`shell.openExternal`](https://github.com/electron/electron/blob/master/docs/api/shell.md#shellopenexternalurl-options) instead of all the mess with `open`/`xdg-open`/`cmd.exe`?

**Comment by blakeembrey** [comment]
It used to, but I need to move away because `dash` had the requirement to be opening in the background (I believe it was for the iOS app integration). See https://github.com/blakeembrey/atom-dash/commit/8a3152abd5e95dc7dd8f449d717ce133581778b3 and https://github.com/blakeembrey/atom-dash/issues/14.

**Comment by blakeembrey** [comment]
What happens if you change `cmd.exe` to just `cmd`? Most examples I've seen are like that, and I'll profess I have no idea when it comes to the windows command - it was contributed by the community.

**Comment by blakeembrey** [comment]
Actually, it looks like I can go back to using `openExternal` now that it accepts an options object. Happy to commit that change now!

**Comment by trollixx** [comment]
What about `activate` option for `shell.openExternal`?

**Comment by blakeembrey** [comment]
@trollixx See https://github.com/blakeembrey/atom-dash/issues/43#issuecomment-250367125. The option was only added this year, I made the other changes a year earlier.

**Comment by trollixx** [comment]
Yeah, noticed that.

**Comment by blakeembrey** [comment]
Ok, pushed that with 1.7.0. Thanks for pointing out the update!

**Comment by trollixx** [comment]
Yeah, testing it right now, and I see a very weird behaviour. There are 3 (!) attempts to run Zeal coming from Atom.

**Comment by trollixx** [comment]
![1475124128](https://cloud.githubusercontent.com/assets/714940/18941269/a1131036-85dd-11e6-877d-57dfd79a51db.png)

**Comment by trollixx** [comment]
I wonder if this is a bug in Electron...
