### ISSUE TITLE
Dash-plugin not working on Windows 10

### ISSUE THREAD

**Issue by laurieny** [blakeembrey/atom-dash#44]
On Windows 10 the plugin for Atom doesn't seem work. If you CTRL + h anything in a file you get an MS pop-up that says "You'll need a new app to open this dash-plugin." Then you are taken to the MS app store, which of course finds nothing.

**Comment by blakeembrey** [comment]
Did you install a Dash compatible app to handle it? I believe Velocity should work for Windows users.

**Comment by trollixx** [comment]
[Zeal](https://zealdocs.org) is another app that supports `dash-plugin` protocol on Windows.

**Comment by laurieny** [comment]
Thank you, I will check that out.

-Laurie

**Comment by blakeembrey** [comment]
Thanks @trollixx, I'll need to update that in the README.

**Comment by laurieny** [comment]
Zeal is working well for me. Thanks@trollixx.
