### ISSUE TITLE
Ctrl-h does not do scoped search/pass in a string to Zeal

### ISSUE THREAD

**Issue by Interagierende-Systeme** [blakeembrey/atom-dash#49]
On Windows 7, Ctrl-h does not return from a scoped search of a custom docset. Instead, it simply opens the Zeal Browser. This does not happen in Linux. I doubt this is an issue in the code base, instead, I am probably doing something wrong. Has anyone else had this problem? Thanks!

**Comment by blakeembrey** [comment]
Is this still happening to you? /cc @trollixx

**Comment by Interagierende-Systeme** [comment]
Yes, but I found out that if I press Ctrl-h again on the function name, it goes to the specific page this time. Have you come across this behavior?

**Comment by blakeembrey** [comment]
Unfortunately I haven't. It sounds like it might be familiar for @trollixx (if I'm remembering correctly), but you can probably log the commands to verify whether it's sending the full query each time (https://github.com/blakeembrey/atom-dash/blob/57bb684b934c1ef8afa82120c5da9123664aba12/lib/dash.coffee#L55).

**Comment by trollixx** [comment]
I'll try to check soon. No ETA, as I am currently relocating...

**Comment by blakeembrey** [comment]
No rush. Where are you relocating to?

**Comment by trollixx** [comment]
@blakeembrey I was in Moscow in June, now in Tel Aviv.

@Interagierende-Systeme I cannot reproduce your problem with the most recent [Zeal CI build](https://bintray.com/zealdocs/windows-ci/zeal-unstable/view), please give it a try. Also I am on Windows 10, not Windows 7.

**Comment by Interagierende-Systeme** [comment]
Thank you all for the replies, I will get back to you with any more findings.

**Comment by flamein** [comment]
For me it doesn't work either, i'm on Fedora 26 using 0.4.0 from fedora repo

**Comment by Interagierende-Systeme** [comment]
I do not have this problem anymore with the Zeal 0.4.0 update.
