### ISSUE TITLE
ctrl+h returns error "The specified location is not supported"

### ISSUE THREAD

**Issue by Bulmer** [blakeembrey/atom-dash#50]
Failed to open URI "dash-plugin:query=read" when cursor is on "read" word (or any other word) in bashscript. Is there a setting I need to adjust here somewhere? I have Atom installed in Debian.

**Comment by blakeembrey** [comment]
Have you installed a Zeal?

**Comment by Bulmer** [comment]
Ok thanks @blakeembrey. I did note that the docs said "This plugin also works with Velocity or Zeal on Windows, and Zeal on Linux." , but I wasn't sure if it needed to be installed. Cheers.

**Comment by blakeembrey** [comment]
Ah, I see. Feel free to submit a PR if that can be clarified. The intent of the message was it works with those "in addition" to Dash on Mac, so I'd love if there's a clearer way to word it.
